export const DataBase = [
  {
    products: [
      {
        id: 1,
        name: "Men's Casual Shirt",
        category: "men",
        subcategory: "shirts",
        brand: "UrbanVibe",
        price: 799,
        mrp: 999,
        discount: "20%",
        sizes: ["S", "M", "L", "XL"],
        colors: ["blue", "white"],
        images: ["/images/men_shirt_1.jpg", "/images/men_shirt_1_2.jpg"],
        stock: 45,
        rating: 4.3,
        reviewsCount: 64,
        description: "Slim fit casual shirt, 100% cotton. Machine washable.",
        tags: ["casual", "cotton", "summer"],
        createdAt: "2025-11-20T08:30:00Z",
      },
      {
        id: 2,
        name: "Women's A-line Dress",
        category: "women",
        subcategory: "dresses",
        brand: "Luna",
        price: 1499,
        mrp: 1999,
        discount: "25%",
        sizes: ["S", "M", "L"],
        colors: ["red", "black"],
        images: ["/images/women_dress_1.jpg"],
        stock: 20,
        rating: 4.7,
        reviewsCount: 112,
        description:
          "Elegant A-line midi dress, suitable for parties and office.",
        tags: ["party", "elegant"],
        createdAt: "2025-10-05T11:00:00Z",
      },
      {
        id: 3,
        name: "Kids' Denim Jacket",
        category: "child",
        subcategory: "jackets",
        brand: "TinyTrendz",
        price: 999,
        mrp: 1299,
        discount: "23%",
        sizes: ["2Y", "3Y", "4Y", "5Y"],
        colors: ["blue"],
        images: ["/images/kids_jacket_1.jpg"],
        stock: 33,
        rating: 4.5,
        reviewsCount: 28,
        description: "Soft denim jacket for kids, breathable and comfortable.",
        tags: ["denim", "kids", "outerwear"],
        createdAt: "2025-09-15T09:20:00Z",
      },
      {
        id: 4,
        name: "Men's Running Shoes",
        category: "men",
        subcategory: "shoes",
        brand: "RunFast",
        price: 2199,
        mrp: 2599,
        discount: "15%",
        sizes: [7, 8, 9, 10, 11],
        colors: ["black", "grey"],
        images: ["/images/men_shoes_1.jpg"],
        stock: 12,
        rating: 4.1,
        reviewsCount: 40,
        description: "Lightweight running shoes with cushioned sole.",
        tags: ["sports", "running"],
        createdAt: "2025-11-30T07:10:00Z",
      },
      {
        id: 5,
        name: "Girls' Frock Floral",
        category: "child",
        subcategory: "dresses",
        brand: "LittleChic",
        price: 699,
        mrp: 899,
        discount: "22%",
        sizes: ["1Y", "2Y", "3Y", "4Y"],
        colors: ["pink"],
        images: ["/images/girls_frock_1.jpg"],
        stock: 50,
        rating: 4.8,
        reviewsCount: 76,
        description: "Soft cotton frock with floral print for toddlers.",
        tags: ["cotton", "toddler"],
        createdAt: "2025-08-02T10:00:00Z",
      },
    ],
    categories: [
      { id: "men", title: "Men" },
      { id: "women", title: "Women" },
      { id: "child", title: "Child" },
    ],
    brands: [
      { id: "urbanvibe", name: "UrbanVibe" },
      { id: "luna", name: "Luna" },
      { id: "tinytrendz", name: "TinyTrendz" },
      { id: "runfast", name: "RunFast" },
      { id: "littlechic", name: "LittleChic" },
    ],
    banners: [
      {
        id: 1,
        title: "Winter Sale - Up to 50% Off",
        image: "/images/banner1.jpg",
        category: "women",
      },
    ],
  },
];
